#!/usr/bin/env bash
# =============================================================================
# Kora Protocol — TTL Keeper
#
# Periodically queries each contract's active persistent keys and proactively
# bumps their TTL before they expire. On Soroban, persistent entries that are
# not touched before their TTL expires get archived/lost.
#
# This script is idempotent and safe to run on a schedule (cron / GitHub Actions).
# TTL bumps are executed via `extend_ttl` which is a public ledger operation —
# no privileged keys are required for reading, but bumping TTL requires a
# funded source account to pay the rent extension fee.
#
# Usage:
#   DEPLOYER_SECRET=<key-or-identity> ./scripts/ttl_keeper.sh [testnet|mainnet]
#
# Environment:
#   DEPLOYER_SECRET  — Stellar secret key or identity name (for paying rent fees)
#   DEPLOYMENT_FILE  — (optional) path to deployment manifest JSON
#
# The script reads contract IDs from the deployment manifest generated by
# deploy.sh at deployments/<network>.json.
# =============================================================================

set -euo pipefail

NETWORK="${1:-testnet}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_LOG="${DEPLOYMENT_FILE:-$ROOT_DIR/deployments/$NETWORK.json}"

# ── Network config ───────────────────────────────────────────────────────────

case "$NETWORK" in
  testnet)
    RPC_URL="https://soroban-testnet.stellar.org"
    NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
    ;;
  mainnet)
    RPC_URL="https://soroban-mainnet.stellar.org"
    NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
    ;;
  *)
    echo "Unknown network: $NETWORK. Use 'testnet' or 'mainnet'."
    exit 1
    ;;
esac

SOURCE="${DEPLOYER_SECRET:-}"
if [ -z "$SOURCE" ]; then
  echo "ERROR: Set DEPLOYER_SECRET environment variable."
  exit 1
fi

if [ ! -f "$DEPLOY_LOG" ]; then
  echo "ERROR: Deployment manifest not found at $DEPLOY_LOG"
  echo "Run deploy.sh first, or set DEPLOYMENT_FILE."
  exit 1
fi

# ── Read contract IDs from deployment manifest ──────────────────────────────

ACCESS_CONTROL_ID=$(jq -r '.contracts.access_control' "$DEPLOY_LOG")
INVOICE_NFT_ID=$(jq -r '.contracts.invoice_nft' "$DEPLOY_LOG")
TREASURY_ID=$(jq -r '.contracts.treasury' "$DEPLOY_LOG")
POOL_ID=$(jq -r '.contracts.financing_pool' "$DEPLOY_LOG")
MARKETPLACE_ID=$(jq -r '.contracts.marketplace' "$DEPLOY_LOG")
RISK_REGISTRY_ID=$(jq -r '.contracts.risk_registry' "$DEPLOY_LOG")

echo "=== Kora TTL Keeper ==="
echo "Network : $NETWORK"
echo "Time    : $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

# ── Helpers ──────────────────────────────────────────────────────────────────

ERRORS=0

invoke() {
  local contract_id="$1"
  local fn="$2"
  shift 2
  stellar contract invoke \
    --id "$contract_id" \
    --source "$SOURCE" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" \
    -- "$fn" "$@" 2>&1
}

# Touch a view function to trigger the contract's internal TTL bump logic.
# Most view functions in Kora contracts call bump_persistent() on read,
# which extends the TTL of the accessed key.
touch_key() {
  local label="$1"
  local contract_id="$2"
  local fn="$3"
  shift 3

  if result=$(invoke "$contract_id" "$fn" "$@" 2>&1); then
    echo "  [OK]   $label"
  else
    echo "  [SKIP] $label — $result"
    ERRORS=$((ERRORS + 1))
  fi
}

# ── Access Control ───────────────────────────────────────────────────────────
# Persistent keys: Admin, Role(address)
# get_admin triggers a read on the Admin key. Role keys are bumped on
# grant/revoke — the admin role is the critical one to keep alive.

echo "--- access_control ($ACCESS_CONTROL_ID) ---"
touch_key "Admin key" "$ACCESS_CONTROL_ID" "get_admin"

# ── Invoice NFT ──────────────────────────────────────────────────────────────
# Persistent keys: Invoice(id)
# We iterate through known invoice IDs (1..next_id) and read each one.
# get_invoice triggers bump_invoice_ttl internally.

echo "--- invoice_nft ($INVOICE_NFT_ID) ---"
NEXT_ID=$(invoke "$INVOICE_NFT_ID" "next_id" 2>/dev/null || echo "1")
NEXT_ID=$(echo "$NEXT_ID" | tr -d '[:space:]"')

if [ "$NEXT_ID" -gt 1 ] 2>/dev/null; then
  TOTAL=$((NEXT_ID - 1))
  echo "  Found $TOTAL invoice(s) to touch"
  for ((id=1; id<NEXT_ID; id++)); do
    touch_key "Invoice #$id" "$INVOICE_NFT_ID" "get_invoice" --invoice_id "$id"
  done
else
  echo "  No invoices found"
fi

# ── Risk Registry ────────────────────────────────────────────────────────────
# Persistent keys: Admin, InvoiceNft, Verifier(addr), SmeProfile(addr),
#                  DebtorScore(hash)
# get_admin and get_sme_profile both call bump_persistent internally.
# We touch the admin key; SME profiles are bumped on every read via
# get_sme_profile which calls bump_persistent.

echo "--- risk_registry ($RISK_REGISTRY_ID) ---"
touch_key "Admin key" "$RISK_REGISTRY_ID" "get_admin"

# ── Treasury ─────────────────────────────────────────────────────────────────
# Persistent keys: Admin, FeeBps, Collected(token), WhitelistedToken(token)
# get_admin and get_fee_bps read from persistent storage. Treasury's
# bump_persistent is called on writes, but reads of Admin/FeeBps at init
# also set TTL.

echo "--- treasury ($TREASURY_ID) ---"
touch_key "Admin key" "$TREASURY_ID" "get_admin"
touch_key "Fee BPS" "$TREASURY_ID" "get_fee_bps"

# ── Marketplace ──────────────────────────────────────────────────────────────
# Persistent keys: Listing(id), WhitelistedToken(addr)
# Listings are bumped on every write via bump_persistent/bump_listing.
# We touch active listings by reading them.

echo "--- marketplace ($MARKETPLACE_ID) ---"
if [ "$NEXT_ID" -gt 1 ] 2>/dev/null; then
  for ((id=1; id<NEXT_ID; id++)); do
    touch_key "Listing #$id" "$MARKETPLACE_ID" "get_listing" --invoice_id "$id"
  done
else
  echo "  No listings to touch"
fi

# ── Financing Pool ───────────────────────────────────────────────────────────
# Persistent keys: Pool(id), Positions(id)
# get_pool and get_positions read from persistent storage.

echo "--- financing_pool ($POOL_ID) ---"
if [ "$NEXT_ID" -gt 1 ] 2>/dev/null; then
  for ((id=1; id<NEXT_ID; id++)); do
    touch_key "Pool #$id" "$POOL_ID" "get_pool" --invoice_id "$id"
    touch_key "Positions #$id" "$POOL_ID" "get_positions" --invoice_id "$id"
  done
else
  echo "  No pools to touch"
fi

# ── Summary ──────────────────────────────────────────────────────────────────

echo ""
if [ "$ERRORS" -gt 0 ]; then
  echo "=== TTL Keeper complete with $ERRORS skipped key(s) ==="
  echo "Skipped keys may not exist yet (e.g. no invoices minted)."
else
  echo "=== TTL Keeper complete — all keys touched ==="
fi
